haml/haml

lib/haml/template.rb
I ran into this problem while trying to run haml 4.0.6 with actionmailer 4.2.0 with sinatra (or rather without Rails).
```ruby
require 'actionmailer'
require 'haml/template' #NoMethodError: undefined method `env' for Rails:Module
```
This is because actionmailer 4.2.0 now has a runtime dependency in `rails-dom-testing`, which loads Rails module, so, defined?(Rails)=true, but, Rails.env is not defined.
Hope I explained it well enough.
=> [stable] Check for Rails.env instead

REFERENCE.md
=> Fix small typo in REFERENCE.md [ci skip]

.travis.yml
Related to https://github.com/haml/haml/commit/1983bdc551e51703eb9671b5e25c6dadaa9f4665
While we can't use it via 2.3 somehow, we already have ruby-2.3.0 on Travis http://rubies.travis-ci.org/.
=> Use Ruby 2.3.0 on Travis

REFERENCE.md
=> Fix a typo [ci skip]

lib/haml/compiler.rb
Forwardable in ruby 2.4 prints a deprecation warning if forwarding
to a private method (preview2 actually raises an exception).
Haml::Engine forwards precompiled_method_return_value to
Haml::Compiler, so the easiest way to fix this is to make
Haml::Compiler#precompiled_method_return_value public.
=> Fix compiler to work without deprecation on ruby 2.4

lib/haml/template.rb
Released version of Haml doesn't include 520d92cc4f52ffe0983b2760ea798c1680476019 that I put in master 2 years ago, and lack of that causes possible test failures on Rails 5 + rails-controller-testing + haml  (see: https://github.com/rails/rails-controller-testing/issues/24 ).
So let me propose to backport this commit to the stable branch, and release new haml stable gem.
=> Backport ActionView lazy-loading to the stable branch

lib/haml/util.rb
Hey guys!  While profiling my small Sinatra app I found the slowest part was:
```
%self      total      self      wait     child     calls  name
5.52      0.312     0.160     0.000     0.152      128   ERB::Compiler::SimpleScanner2#scan
```
It is being called so many times because ERB.new(erb) is being called from within the powerset enumeration.
This small change eliminated my performance issue, and the haml tests continue to pass on Ruby 2.2.2
=> extract erb object creation out of powerset loop

haml.gemspec, lib/haml/compiler.rb, lib/haml/engine.rb, lib/haml/options.rb, lib/haml/parser.rb, lib/haml/template.rb, lib/haml/temple_engine.rb, test/parser_test.rb
ref: https://github.com/haml/haml/issues/851
I migrated Haml's engine backend to Temple.
In this PR, I didn't change compiler process to temple-AST-based one and make breaking changes. But now `Haml::Parser` and `Haml::Compiler` are on Temple Engine's pipeline.
There is no feature addition or performance improvement but refactoring for future maintainability.
Since I implemented Hamlit v2 with original `Haml::Parser` in https://github.com/k0kubun/hamlit/pull/43, I know we can compile `Haml::Parser::ParseNode` into Temple AST (but not completely compatible about `Haml::Helpers`, though). This is just a first step for a whole migration.
=> Temple migration

lib/haml/compiler.rb, lib/haml/generator.rb, lib/haml/temple_engine.rb
ref: https://github.com/haml/haml/issues/851
I inserted `Haml::Generator` like `Temple::Generator` into `Haml::TempleEngine`. It allows us to use Temple AST to generate compiled Ruby code.
Using that, I added `.freeze` for static string literals for Ruby 2.1+. Whille I'm going to add some changes, this is just a first step.
With [hamlit/benchmark/etc/tags_loop.haml](https://github.com/k0kubun/hamlit/blob/9a0378ed8a09734655a5813a65378a9c157449b3/benchmark/etc/tags_loop.haml) and Ruby 2.4.0,
```
$ bin/bench benchmark/etc/tags_loop.haml
=================================================
Rendering: benchmark/etc/tags_loop.haml
=================================================
haml v5.0.0.beta.2     3.538k i/100ms
faml v0.8.1     4.801k i/100ms …
```
=> Introduce Temple generator and freeze string literals

CHANGELOG.md, lib/haml/template/plugin.rb, lib/haml/temple_engine.rb
- I added `after_preamble` option to have `ActionView::OutputBuffer.new rescue nil` and changed `Haml::Plugin` to use the option.
- `ActionView::OutputBuffer.new rescue nil` has unnecessary overhead for the case `ActionView::OutputBuffer` is not defined. 
- It may improve Tilt's maintainability by using `after_preamble` to insert [this part](https://github.com/rtomayko/tilt/blob/v2.0.6/lib/tilt/haml.rb#L40-L41).
- I also changed `rescue nil` to `if defined?(ActionView::OutputBuffer)` to avoid ignoring unexpected exceptions.
For non-Rails environment, with Ruby 2.4.0 and [hamlit/benchmark/slim/view.haml](https://github.com/k0kubun/hamlit/blob/9a0378ed8a09734655a5813a65378a9c157449b3/benchmark/slim/view.haml),
```
$ ONLY_HAML=1 be ruby benchmark/slim/run-benchmarks.rb
Calculating …
```
=> Add after_preamble hook for precompiled_with_ambles and separate Rails-related code

lib/haml/compiler.rb, lib/haml/generator.rb, test/engine_test.rb, test/pretty_engine_test.rb
related to https://github.com/haml/haml/issues/894
Even though ugly mode is used for production, currently test coverage for ugly mode is poor. So I just copied `EngineTest` as `PrettyEngineTest` and let `EngineTest` test ugly mode. I named not `UglyEngineTest` but `EngineTest` because we'll drop pretty mode in the future.
I fixed `EngineTest`'s test results to be the same as the ugly mode behavior at https://github.com/haml/haml/commit/ed361008151d14c1168a7804f7f2a0d4a414e423.
Also, I fixed unconsidered bugs which I introduced by Temple migration and are detected by these new tests.
=> Add ugly mode tests

lib/haml/buffer.rb, lib/haml/options.rb, lib/haml/railtie.rb, test/options_test.rb
- To reduce object allocations on runtime, I added `Haml::Options.buffer_defaults` to use in `Haml::Buffer#initialize`.
- To avoid allocating new Hash, I changed `Haml::Buffer#initialize` not to call `Hash#merge` if no options are given.
- ~~Use `escape_html: true, ugly: true` as Haml's default options. This change gives significant performance gain for all Rails applications.~~
- ~~related to: https://github.com/haml/haml/issues/894~~
- ~~**This is breaking change.** I think we should ship this change in Haml 6.~~
Preamble code will be changed like:
```diff
-begin;extend Haml::Helpers;_hamlout = @haml_buffer = Haml::Buffer.new(haml_buffer, {:autoclose=>["area", "base", "basefont", "br", "col", "command", "embed", "frame", "hr", "img", "input", "isindex", "keygen", "link", "menuitem", …
```
=> Use Rails default options for Haml's default options

CHANGELOG.md, lib/haml/attribute_builder.rb, lib/haml/helpers.rb, test/engine_test.rb, test/pretty_engine_test.rb, test/pretty_results/just_stuff.xhtml, test/results/just_stuff.xhtml
close https://github.com/haml/haml/issues/901
All details are described in https://github.com/haml/haml/issues/901.
Without implementing Temple compiler for attributes, it improves performance.
With Ruby 2.4.0 and  [k0kubun/haml_bench/templates/slim_bench.haml](https://github.com/k0kubun/haml_bench/blob/97a7b9970684b975c48e1403ee4fe329bf1151fb/templates/slim_bench.haml),
```
$ bundle exec ruby bench.rb
Rendering: /home/k0kubun/src/github.com/k0kubun/haml_bench/templates/slim_bench.haml
haml 4.0.7     4.183k i/100ms
haml 5.0.0.beta.2     5.385k i/100ms
-------------------------------------------------
haml 4.0.7     43.307k (± 1.0%) i/s -    217.516k
haml 5.0.0.beta.2     56.453k (± 1.5%) i/s -    285.405k
Comparison:
haml 5.0.0.beta.2: …
```
=> Simplify HTML escaping

CHANGELOG.md, lib/haml/attribute_builder.rb, test/engine_test.rb, test/pretty_engine_test.rb
`Haml::Helpers.preserve` is very slow. I don't think it's necessary for attributes because Slim, Faml and Hamlit don't preserve them and work fine. 
The original change was done in 2008 https://github.com/haml/haml/commit/e8075e7feac72291a203b137b4f8c2a13457e843 and no reason is found to keep that change. Let's remove a legacy feature.
With Ruby 2.4.0 and  [k0kubun/haml_bench/templates/slim_bench.haml](https://github.com/k0kubun/haml_bench/blob/97a7b9970684b975c48e1403ee4fe329bf1151fb/templates/slim_bench.haml),
```
$ bundle exec ruby bench.rb
Rendering: /home/k0kubun/src/github.com/k0kubun/haml_bench/templates/slim_bench.haml
haml 4.0.7     3.576k i/100ms
haml 5.0.0.beta.2     5.450k i/100ms …
```
=> Don't preserve newlines in attributes

haml.gemspec, lib/haml/attribute_builder.rb, lib/haml/attribute_compiler.rb, lib/haml/attribute_parser.rb, lib/haml/compiler.rb, lib/haml/escapable.rb, lib/haml/temple_engine.rb, lib/haml/temple_line_counter.rb, test/attribute_parser_test.rb, test/temple_line_counter_test.rb
- Implement attribute compiler using Temple
- To compile attributes, introduce attribute parser using Ripper imprted from Hamlit.
- On Ripper-less platforms, attribute compiler isn't applied but it fallbacks to current implementation.
- For almost all cases, we can render attributes without `Haml::Buffer#attributes`, which is a bottleneck of Haml 4.
- Apply Temple's static analyzer to render attributes beforehand
All tests passed without changing behaviors in this branch. They are the last changes I want to release in Haml 5.
With Ruby 2.4.0 and  [k0kubun/haml_bench/templates/slim_bench.haml](https://github.com/k0kubun/haml_bench/blob/8d8cc944bdc1138c58629109b6ecc06e7d5ea1a7/templates/slim_bench.haml),
[the result on Travis](https://travis-ci.org/k0kubun/haml_bench/jobs/199977841)
``` …
```
=> Introduce Temple attribute compiler

CHANGELOG.md, lib/haml/attribute_builder.rb, lib/haml/attribute_compiler.rb, lib/haml/error.rb, test/engine_test.rb
close https://github.com/haml/haml/issues/891
Developers should never embed user's input as attribute name. User's input can include invalid characters defined in [HTML spec](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2). So I changed Haml to raise an error for that case.
For some exceptional cases that developers want to use user's input like `params`'s keys in attribute name, they should handle this exception and respond 4XX errors. It should be 5XX for normal cases.
=> Raise exception for unsafe attribute name

lib/haml/buffer.rb, lib/haml/compiler.rb
I changed to generate `_hamlout.fix_textareas!(::Haml::Helpers.html_escape(i[:name].to_s))` instead of `_hamlout.format_script(i[:name],false,false,true,false)`.
With this change, we can avoid some unnecessary method calls' overhead without changing behaviors.
With Ruby 2.4.0 and [k0kubun/haml_bench/templates/slim_bench.haml](https://github.com/k0kubun/haml_bench/blob/833f04306bc138261d8d2102a4f0cceb3a78eca7/templates/slim_bench.haml),
```
Rendering: /home/travis/build/k0kubun/haml_bench/templates/slim_bench.haml
Warming up --------------------------------------
haml 4.0.7     1.648k i/100ms
haml 5.0.0.beta.2     5.737k i/100ms
haml 4.0.7     18.380k (± 2.4%) i/s -     92.288k in   5.024238s
haml 5.0.0.beta.2     64.617k (± 1.4%) i/s - …
```
=> Resolve overhead of calling Haml::Buffer#format_script

lib/haml/railtie.rb
Early loading causes a conflict with rspec and view specs.
See issue to reproduce: https://github.com/haml/haml/issues/883
I tried to ensure all the modules are loaded using the `ActiveSupport.on_load` mechanism to avoid further problems. Because I'm not sure all the situations that haml is used in, I did a fairly robust (conservative) approach.
This fix should be forward ported to `haml5`.
=> Do not load modules early when in rails

lib/haml/railtie.rb, lib/haml/template/options.rb, test/options_test.rb
Fix test failure caused by https://github.com/haml/haml/commit/c9472d0633d8c93c642876c2100f57a9ab21721a.
@amatsuda WDYT?
=> Fix buffer_options test to assume Rails environment

lib/haml/sass_rails_filter.rb
- Fixes #844
- Sprockets 3 changed Sprockets::Context#initialize to take a hash
argument
- This makes haml incompatible with inline sass for sprockets 2.x but
since the last sprockets 2.x release was in 2014 this is probably acceptable
=> Make inline sass work with sprockets 3.x

.yardopts, Gemfile
> Attributes: `
> http://haml.info/docs/yardoc/file.REFERENCE.html#attributes_
> Attributes: {} or ()
=> Fix title of REFERENCE Attributes section

lib/haml/parser.rb, test/results/bemit.xhtml, test/template_test.rb, test/templates/bemit.haml
CSS conventions including [BEMIT](http://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further) encourage use of the `@` sign in CSS class names as part of [a suffix indicating the breakpoint at which a class takes effect.](http://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further#responsive-suffixes)
This PR adds Haml support for `@` within class names, so we can do:
``` haml
.o-media@md
```
Instead of having to do:
``` haml
%div{class: 'o-media@md'}
```
A passing test is included.
=> Add support for CSS class names containing the `@` sign ("commercial at", U+0040)

CHANGELOG.md
By identifying breaking changes in the changelog, it will be much easier for people to upgrade to 5.
Not being a HAML expert, I may have missed some breaking changes, but this should be a good start.
=> Docs: Help people upgrade to 5 by classifying changes

haml.gemspec
Since Haml includes symlink in test directory and doesn't exclude in gem package, gem installation is broken on Windows https://github.com/haml/haml/issues/919.
Current files are just legacy as it's originally defined in 11 years ago https://github.com/haml/haml/commit/b88841e6d30cfd5fffc0744994fb7d5ad2d9f07d.
To remove at least `test/*` files to fix #919, I replaced it with [bundle gem's template](https://github.com/bundler/bundler/blob/1624e5775acab1b18743aabfb4ed2045d368d9e9/lib/bundler/templates/newgem/newgem.gemspec.tt#L28-L30) modified a little.
```
test/attribute_parser_test.rb
test/engine_test.rb
test/erb/_av_partial_1.erb
test/erb/_av_partial_2.erb
test/erb/action_view.erb
test/erb/standard.erb
test/filters_test.rb
test/gemfiles/Gemfile.rails-4.0.x …
```
=> Modernize Gem::Specification#files and remove test from it

CHANGELOG.md
An example will help people (like me) understand this breaking change.
I think that JSON is a common place where this breaking change will affect people. It caught me. That's why I chose JSON for the example, but maybe a simpler example would be better?
[ci skip]
=> Docs: Clarify changes to escaping of quotes

lib/haml/compiler.rb, lib/haml/helpers/safe_erubi_template.rb, lib/haml/options.rb, lib/haml/railtie.rb, lib/haml/temple_engine.rb, test/filters_test.rb, test/template_test.rb
To avoid changing template handler globally, I added `:filters` option to override filter compiler with Rails-specific template handler. With this change, Erubi/Erubis handler in ActionView is never used for non-Rails apps.
You may notice "test/filters_test.rb" is changed. But such change may occur only in the situation both Rails and non-Rails app rendering Haml templates exist (in other words, they will have breaking change. However, duplicating last newline may not affect a behavior on browser). Thus in pure Sinatra environment, there'll be no breaking change.
While Erubi and Erubis renders templates slightly differently for last newline, I think that's Rails' breaking change and not Haml's one.
=> Use Erubi/Erubis only in Rails template handler

lib/haml/helpers.rb, test/helper_test.rb
Hello,
The current `list_of` helper in haml 5.0.1 seem to have an issue when running in rails (at least in 5.0.0.1) when inserting multi-line content. 
In my rails app when I do a block `link_to` in the `list_of`, the content of the list is removed:
```
= list_of array do |type|               
= link_to helper_url(type) do            
= myhellper(type)                                         
= type.humanize 
```
It seem to be linked to the use of `strip!` instead of `strip` the `!` version will actually return [nil if does nothing](https://ruby-doc.org/core-2.2.0/String.html#method-i-strip-21).
I managed to add a test that seem to replicate the issue without rails. It could also probably be fixed using an `result.strip! || result` which would not copy `result`.
Thanks again for HAML and …
=> Fix list_of helper with multi-line content

lib/haml/buffer.rb, lib/haml/compiler.rb, lib/haml/helpers/action_view_mods.rb
We call `Haml::Buffer#fix_textareas!` to rollback textarea content's first `&#x000A;`, which is unexpectedly preserved from `\n` by `Haml::Helpers#preserve`, to `\n` for every script.
But it means that we need to call `Haml::Buffer#fix_textareas!` only after we call `preserve`. So I fixed to do so.
With Ruby 2.4.0 and [k0kubun/haml_bench/templates/slim_bench.haml](https://github.com/k0kubun/haml_bench/blob/833f04306bc138261d8d2102a4f0cceb3a78eca7/templates/slim_bench.haml),
```
haml 4.0.7     41.534k (± 1.4%) i/s -    210.652k in   5.072717s
haml 5.0.1    138.067k (± 1.5%) i/s -    700.872k in   5.077348s
Comparison:
haml 5.0.1:   138067.3 i/s
haml 4.0.7:    41534.1 i/s - 3.32x  slower
```
```
Calculating …
```
=> Fix textareas only after preserved timing

lib/haml/railtie.rb
ActionView prior to 5.1 does not support Erubi. haml was looking for existence of `Erubi` in the bundle, and then assuming that ActionView would support it.
This checks directly for ActionView to support Erubi rather than only looking to see if Erubi is in the bundle at all. In effect, this causes haml to use Erubis in Rails prior to 5.1.
This change is necessary because `Haml::ErubiTemplateHandler` inherits from `ActionView::Template::Handlers::ERB::Erubi`, which in Rails prior to 5.1 is actually a reference to the `Erubi` _module_, not actually a useable class. A class inheriting from a module causes a fatal exception (which can be seen in #946).
I tested this with Rails 5.0 with and without erubi in the bundle, and with Rails 5.1 with and without erubis in the bundle. (I mention this …
=> Fix Erubi on Rails < 5.1

.travis.yml, test/gemfiles/Gemfile.rails-5.0.x.erubi, test/test_helper.rb
We found an issue, fixed in #948, that was caused by Erubi being loaded. The way to reproduce this was to require erubi while Rails 5.0 is in use.
I wanted to add test coverage for this, so I added a gemfile that includes rails 5.0 and erubi. This didn't reproduce the issue though, because in test_helper, only specific gems are required directly. Since `Bundler.require` is not used, only dependencies that are directly required will be available in the tests.
There seem to be two options:
1. Add `require` calls for erubi and rescue from failure.
2. Add `Bundler.require` to test_helper and allow it to load everything that's included in each gemfile.
I advocate 2 because it is closest to the way Rails works. I assume that the long-term goal is to remove Rails from this project completely in …
=> Require entire bundle in tests, add test case for Rails 5.0 with Erubi

.travis.yml, lib/haml/railtie.rb
This was attempted in #948, but we made a small change after the PR was first opened. Turns out we must use check for Erubi using `defined?` and Rails' Erubi object using `const_defined?`.
If we call `defined?` with Rails's object, it gets defined by Rails. Calling `const_defined?` with the constant as a string seems to be the only way for us to see if it's been defined without _causing it to be defined_.
Without the `defined?` in front of the `const_defined?` call, Rails 4.2 raises a weird exception. Together, they seem to do the job.
I've set Travis to require the erubi gemfile tests to pass.
=> Re-fix Erubi on Rails < 5.1

.yardopts
Updating the `--exclude` path to `plugin.rb`, and removing the entry for `patch.rb` in `.yardopts` file.
=> Tidy up --exclude options in .yardopts

CHANGELOG.md, lib/haml/buffer.rb
Stringifying the keys of a hash can be done without allocating many
arrays like the previous approach did.
```ruby
begin
require "bundler/inline"
rescue LoadError => e
$stderr.puts "Bundler version 1.10 or later is required. Please update
your Bundler"
raise e
end
gemfile(true) do
source "https://rubygems.org"
gem "benchmark-ips"
end
def allocate_count
GC.disable
before = ObjectSpace.count_objects
yield
after = ObjectSpace.count_objects
after.each { |k,v| after[k] = v - before[k] }
after[:T_HASH] -= 1 # probe effect - we created the before hash.
GC.enable
result = after.reject { |k,v| v == 0 }
GC.start
result
end
@old = {a: :b, c: :d, e: :f}
def master_version
Hash[@old.map { |k, v| [k.to_s, v] }]
end
def fast_version
result = {}
@old.each { |k, v| result[k.to_s] = v }
end
puts …
```
=> Rewrite old attribute mapping to save many object allocations

CHANGELOG.md, lib/haml/util.rb
In micro-benchmarking, this change performs within margin of error of
the existing code but saves a string allocation each time the method is
called (assuming the quote strings in the old code were frozen).
```
begin
require "bundler/inline"
rescue LoadError => e
$stderr.puts "Bundler version 1.10 or later is required. Please update
your Bundler"
raise e
end
gemfile(true) do
source "https://rubygems.org"
gem "benchmark-ips"
end
def allocate_count
GC.disable
before = ObjectSpace.count_objects
yield
after = ObjectSpace.count_objects
after.each { |k,v| after[k] = v - before[k] }
after[:T_HASH] -= 1 # probe effect - we created the before hash.
GC.enable
result = after.reject { |k,v| v == 0 }
GC.start
result
end
interpolated = "hi"
puts "'"' + interpolated + '"'"
puts allocate_count { …
```
=> Replace interpolated interpolation with cleaner method

lib/haml/compiler.rb, lib/haml/engine.rb, lib/haml/filters.rb, lib/haml/generator.rb, lib/haml/helpers.rb, lib/haml/parser.rb, lib/haml/temple_engine.rb, lib/haml/util.rb, test/attribute_parser_test.rb, test/filters_test.rb, test/helper_test.rb, test/options_test.rb, test/parser_test.rb, test/template_test.rb, test/template_test_helper.rb, test/temple_line_counter_test.rb, test/util_test.rb
I was able to get `frozen_string_literal: true` turned on in two files. Unfortunately I wasn't able to get them on in the rest, the majority of which were because of various calls to `rstrip!` and `tr!` which are more performant in micro-benchmarks and in memory usage. I made other changes in these files to string builder logic such that they no longer mutate strings, based on [this](https://stackoverflow.com/questions/6549074/whats-the-fastest-way-to-build-a-string-in-ruby) StackOverflow post.
String mutations preventing `frozen_string_literal: true`
`lib/haml/compiler.rb` - [rstrip!](https://github.com/q-centrix/haml/blob/master/lib/haml/compiler.rb#L318)
`lib/haml/filters` - [rstrip!](https://github.com/q-centrix/haml/blob/master/lib/haml/filters.rb#L251)
`lib/haml/template_engine.rb` …
=> Frozen string literal changes

lib/haml/temple_engine.rb
Fixes #982.
This PR maintains public-API compatibility in `Haml::TempleEngine#precompiled_with_return_value` and `precompiled_with_ambles`, returning mutable strings as expected by `tilt`'s Haml template implementation (which [calls `#force_encoding` on the result](https://github.com/rtomayko/tilt/blob/70000d8af45f7020a88f796b056cc0a1be2410dd/lib/tilt/template.rb#L188-L195)).
=> un-freeze TempleEngine precompiled string literals

REFERENCE.md, lib/haml/filters.rb, lib/haml/options.rb, lib/haml/temple_engine.rb
Addresses points raised in (closed issue) #940, by allowing optional backwards compatibility to work around breaking changes introduced by #770 (released in [`5.0.0`](https://github.com/haml/haml/blob/master/CHANGELOG.md#500)).
This PR is mostly intended for migrating large/legacy applications written against the v4 API, that want to upgrade to v5 while avoiding time-intensive application refactoring (e.g., https://github.com/haml/haml/issues/940#issuecomment-329769397).
My particular use-case is a need to upgrade `haml` to `>= 5.0.4` for [Ruby 2.5 support](https://github.com/haml/haml/blob/master/CHANGELOG.md#504) without refactoring large amounts of existing application code.
Introduces a new `escape_interpolated_html` option (defaults to the current value of `escape_html` for backwards …
=> add escape_interpolated_html option

lib/haml/plugin.rb
In Rails 6 the API for template handlers is changing, a template handler
must now take two arguments [1], the template and the source, otherwise you
will see the following deprecation warning:
```
ActiveSupport::DeprecationException: DEPRECATION WARNING: Single arity
template handlers are deprecated.  Template handlers must now accept two
parameters, the view object and the source for the view object.
Change:
>> Class#call(template)
To:
>> Class#call(template, source)
```
I have attempted to retain support for older versions of Rails by
providing a default source of `nil`.
[1] https://www.github.com/rails/rails/commit/28f88e0074
=> Add support to `Haml::Plugin` for Rails 6

haml.gemspec
I've added additional links to metadata to be able to go quickly to relevant pages from rubygems.org
Relevant docs: https://guides.rubygems.org/specification-reference/#metadata
=> Add metadata URLs

lib/haml/parser.rb, test/parser_test.rb
Since newrelic is using the `#inspect` method on `ParseNode` the ruby code crashes due to frozen strings in `inspect`, which are recursively called with `gsub!` causing this error:
I added a regression test that fails with the current code.
=> Unfreeze string literals for ParseNode#inspect

.gitignore, test/test_helper.rb
The README specifies that you can run `rake` in order to successfully pass the test suite.
Unfortunately, due to the include order in the test_helper, you actually have to run `bundler exec rake`.
We were already partially setting up Bundler in the `test_helper`, and this makes it startup properly.
=> Fix Test Suite with Bundler

lib/haml/attribute_builder.rb, test/engine_test.rb, test/helper_test.rb, test/results/helpful.xhtml, test/results/just_stuff.xhtml
Since Ruby 1.8.7 is no longer supported, and therefore the Array `|`
method preserves the order of their elements, there should be no technical
need to sort class names of Haml tags.
In addition to likely boosting performance (one less array instantiated
per tag, though I did not run any benchmarks), this fixes weird
interactions that Haml has with libaries like Hamlbars.
Take, for instance:
`%section.class-name{ class: "{{ maybe ? 'top' : 'bottom' }}" }`
When class names are sorted, the contents of the curly-braces
expression gets reordered so that it's no longer valid Handlebars.
By not sorting, the two sources of classes (`.class-name` and the
`class` attribute) get merged without disrupting the Handlebars.
=> Preserve order of class names in Haml tags

lib/haml/parser.rb, test/engine_test.rb
Currently `text.haml` files are html escaped. This PR fixes that.
Related to haml/haml#1014 and haml/haml-rails#163
=> Do not run escape_html on text/plain files

CHANGELOG.md, REFERENCE.md, test/engine_test.rb
Update the haml-spec submodule, added text to the REFERENCE file specifying this behaviour, and also added a more comprehensive test case.
=> Reorder Class Names Follow Up

lib/haml/attribute_builder.rb, lib/haml/attribute_compiler.rb, lib/haml/escapable.rb, lib/haml/helpers.rb, lib/haml/helpers/xss_mods.rb, test/results/escape_safe_buffer.xhtml, test/template_test.rb, test/templates/escape_safe_buffer.haml
Fixes #993, fixes #1019
Like rails helpers fixed in CVE-2016-6316, an attribute should be HTML-escaped even if it's a SafeBuffer.
=> Escape attributes regardless of whether it's SafeBuffer or not

.travis.yml, haml.gemspec, lib/haml/util.rb, test/cases/engine_internals_test.rb, test/cases/nesting_test.rb, test/cases/ruby_multiline_test.rb
https://github.com/haml/haml/pull/967 added the frozen string literal magic comments on all ruby files.
To ensure that the strings are not modified in the future, I think the tests also should cover it. This PR fixes a string mutation case and runs tests with `RUBYOPT=--enable-frozen-string-literal`, where the ruby interpreter will ensure the frozen strings.
=> Enable frozen string literal

lib/haml/parser.rb, test/cases/attribute_test.rb, test/cases/exception_test.rb
Fixes #981.
This is ported from [Hamlit v1 code](https://github.com/k0kubun/hamlit/blob/v1.7.2/lib/hamlit/parsers/attribute.rb#L29-L43) which supported multiline attributes. It was dropped when Hamlit started using Haml's parser in v2, but I'd be happy to resurrect the support. Please read the code comments for design decision details.
=> Implement multiline attributes

lib/haml/attribute_builder.rb, lib/haml/attribute_compiler.rb, lib/haml/buffer.rb
This is one obvious way to reduce `Haml::Buffer` dependencies. This should have no impact.
=> Drop Haml::Buffer dependency from attributes

CHANGELOG.md, lib/haml/plugin.rb, lib/haml/railtie.rb, lib/haml/temple_engine.rb, test/template_test.rb
Rails 6.1 adds a `ActionView::Base.annotate_rendered_view_with_filenames` option, but it's ERB-only (https://github.com/rails/rails/blob/89b52a8dd35cd90e0de05aa2ddc3f5b61832a269/actionview/lib/action_view/template/handlers/erb.rb#L53-L56)
How about something like this?  It adds filename comments into the html looking like, eg:
```html
<div class='navbar-light navbar-collapse collapse wi-100 d-md-none' id='navbar-collapse'>
<div class='navbar-nav phm mbm' role='menu'>
<a class="nav-link" href="/profile">Profile</a>
<a class="nav-link" href="/account/edit">Settings</a>
<div class='dropdown-divider'></div>
<a class="nav-link" href="/logout">Log out</a>
```
Not sure how clean the implementation is, let me know if there's a more suitable place to insert these.
=> Add support for annotate_rendered_view_with_filenames

lib/haml/compiler.rb, lib/haml/compiler/script_compiler.rb, lib/haml/engine.rb, lib/haml/rails_template.rb, test/hamlit/engine/script_test.rb, test/hamlit/engine/whitespace_test.rb, test/hamlit/line_number_test.rb
This resurrects the block-capturing support of `Tilt::HamlTemplate` https://github.com/rtomayko/tilt/issues/325. It has been broken since v5, and this pull request fixes it by porting Hamlit 3's patch https://github.com/k0kubun/hamlit/compare/v2.16.0...v3.0.0 to Haml 6.
=> Resurrect block capturing support for non-Rails environments

REFERENCE.md
In Haml 6, the suggested code for using Haml programmatically was changed from `Haml::Engine` to `Haml::Template`. This PR adjusts the mention of `Haml::Engine` in the line before to be in line with the example code.
=> Remove mention of `Haml::Engine` in favor of `Haml::Template`

lib/haml/util.rb
This is a follow-up commit for 8f29bed6ae292bcef8b82cc2baf99a423e2d6191
=> Fallback to Ruby instead of C ext in util.rb also

REFERENCE.md
In the updated documentation, it is explained that only the `Haml::AttributeBuilder::BOOLEAN_ATTRIBUTES` are treated as boolean attributes. While testing this, I noticed that this also still works for `data-` and `aria-` attributes.
This makes sense, since this is exactly what the code does:
https://github.com/haml/haml/blob/b3cdafdaf09433af4b0988a533414d9409e72f2a/lib/haml/attribute_compiler.rb#L55
So I think it might be a good addition to the docs to mention this explicitely.
Thanks for your consideration!
=> Explain special case of `data-` and `aria-` attributes

lib/haml/rails_template.rb
Currently haml forces ActionView::Base to load very early in the initialization process, which can cause it to ignore config settings in config/initializers. How about this change to delay the `include Haml::RailsHelpers` until ActionView is ready?
=> Avoid loading ActionView::Base too early

REFERENCE.md
Hello, I’m not an English native, but I saw you made 2 mistakes in your reference:
* “brackets” alone means “parentheses”; for `{}` you must say “curly brackets” or “braces”;
* in English they say “replace with” (not “replace by”, although in my language, we say “by”).
I don’t know if my pull request targets the right branch as the info on https://haml.info/development.html is outdated.
=> REFERENCE.md: replace ‘bracket’ with ‘brace’

haml.gemspec
Make the gem more secure by requiring that all privileged operations by any of the owners require OTP.
Ref: https://guides.rubygems.org/mfa-requirement-opt-in/
=> Opt-in for MFA requirement

lib/haml/rails_template.rb
I want to make haml autogenerate id attributes for all elements. The ids should be static at runtime, so my idea was to use a hash of "#{filename}:#{line}". While trying to implement it, I noticed the filename is currently not set. This tiny patch fixes it.
=> Use the rails template path as filename

lib/haml/rails_template.rb
=> add default_format method to RailsTemplate for Turbo compatibility

README.md, lib/haml/parser.rb, test/haml/engine/silent_script_test.rb, test/haml/helper_test.rb
WDYT to adding case-in support?
```haml
- case type_and_details
- in [:user_account, user]
Profile #{user.name}
- in [:post, post]
Post #{post.title}
```
Let me know if you think it needs more tests. I looked at adding some to engine_tests.rb, but they seem more like regression tests, wasn't sure of the best place to add it.
=> Add support for case-in statements

haml.gemspec
By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/haml which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/
=> Provide a 'Changelog' link on rubygems.org/gems/haml

REFERENCE.md
The `Haml::AttributeBuilder::BOOLEAN_ATTRIBUTES` was replaced with `Haml::BOOLEAN_ATTRIBUTES` in cb9cc050.
This commit fixes REFERENCE.md to keep the documentation up-to-date.
=> Replace `Haml::AttributeBuilder::BOOLEAN_ATTRIBUTES` in REFERENCE.md

test/haml/engine_test.rb
Method names are quoted with ''
https://bugs.ruby-lang.org/issues/16495
Method names include method owner
https://bugs.ruby-lang.org/issues/19117
I hope this would fix the broken CI.
=> Backtrace format has been changed since Ruby 3.4

lib/haml/attribute_builder.rb
Hello, this is my first contribution to production code. I've checked `git blame` 6d71b6e757d1e5759d85a68e98ed421c552b72e1 and the usage of `gsub` does not look intended, so maybe this change is legit.
Benchmarks have been executed on M1 Pro, Ruby 3.3.4 x64
---
This change was flagged by RuboCop and has been verified for correctness and performance improvement. While Ruby 2.1 is no longer tested in CI, `String#tr` is supported since that version, ensuring backwards compatibility.
- Replace `gsub(/_/, '-')` with `tr('_', '-')` for better performance
- Improve `bench benchmark/data_attribute.haml` execution time by 20%
- Maintain compatibility with Ruby 2.1 (Haml's minimum required version)
Before:
```
haml v6.3.0     94.400k i/s (0.011ms) -    473.668k
haml v6.3.0     3.264k memsize ( …
```
=> Optimize string transformation using `String#tr`
